apiVersion: v1
kind: Template
metadata:
  name: wordpress-openshift-template-redhat
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wordpress
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: wordpress
      template:
        metadata:
          labels:
            app: wordpress
        spec:
          containers:
            - name: wordpress
              # Red Hat UBI-based WordPress image from the Red Hat container catalog
              image: registry.redhat.io/rhel8/wordpress-php
              ports:
                - containerPort: 8080
              env:
                - name: WORDPRESS_DB_HOST
                  value: mysql
                - name: WORDPRESS_DB_USER
                  value: user
                - name: WORDPRESS_DB_PASSWORD
                  value: password
                - name: WORDPRESS_DB_NAME
                  value: wordpressdb
              securityContext:
                runAsUser: 1001
                allowPrivilegeEscalation: false
              volumeMounts:
                - mountPath: /var/www/html/wp-content
                  name: wordpress-storage
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: wordpress-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mysql
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mysql
      template:
        metadata:
          labels:
            app: mysql
        spec:
          containers:
            - name: mysql
              # MySQL image from the Red Hat container catalog
              image: registry.redhat.io/rhel8/mysql-80
              ports:
                - containerPort: 3306
              env:
                - name: MYSQL_ROOT_PASSWORD
                  value: rootpassword
                - name: MYSQL_DATABASE
                  value: wordpressdb
                - name: MYSQL_USER
                  value: user
                - name: MYSQL_PASSWORD
                  value: password
              securityContext:
                runAsUser: 1001
                allowPrivilegeEscalation: false
              volumeMounts:
                - mountPath: /var/lib/mysql/data
                  name: mysql-storage
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mysql-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: Service
    metadata:
      name: wordpress
    spec:
      selector:
        app: wordpress
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
  - apiVersion: v1
    kind: Route
    metadata:
      name: wordpress
    spec:
      to:
        kind: Service
        name: wordpress
      port:
        targetPort: 8080